###
GET http://localhost:3001/tasks

###
POST  http://localhost:3001/tasks
Content-Type: application/json
  
{
  "title": "Task",
  "description": "Task description",
  "isCompleted": false,
  "priority": "HIGH"
}

###
