###
GET http://localhost:3001/tasks

###
POST  http://localhost:3001/tasks
Content-Type: application/json
  
{
  "title": "Task",
  "description": "Task description",
  "isCompleted": false,
  "priority": "HIGH"
}

###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "jean@example.com",
  "password": "123456"
}

###
GET http://localhost:3001/auth/users/